import './globals.css'
import localFont from 'next/font/local';
const Poppins = localFont({
  src: '../../public/poppins.ttf',
  display: 'swap',

});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Poppins.className}>{children}</body>
    </html>
  )
}
